# Squashed migration for common app - combines all previous migrations
# Generated by squashing 0001_initial, 0002_initial, 0003_add_clinical_insight, 0004_enable_pg_extensions

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def enable_pg_extensions(apps, schema_editor):
    """Enable PostgreSQL extensions - only runs on PostgreSQL."""
    if schema_editor.connection.vendor != 'postgresql':
        return
    
    extensions = [
        'vector', 'pg_trgm', 'pg_cron', 'uuid-ossp', 'btree_gin', 'btree_gist'
    ]
    for ext in extensions:
        schema_editor.execute(f'CREATE EXTENSION IF NOT EXISTS "{ext}";')


def disable_pg_extensions(apps, schema_editor):
    """Disable PostgreSQL extensions - only runs on PostgreSQL."""
    if schema_editor.connection.vendor != 'postgresql':
        return
    
    extensions = [
        'vector', 'pg_trgm', 'pg_cron', 'uuid-ossp', 'btree_gin', 'btree_gist'
    ]
    for ext in reversed(extensions):
        schema_editor.execute(f'DROP EXTENSION IF EXISTS "{ext}";')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Enable PostgreSQL extensions first (PostgreSQL only)
        migrations.RunPython(enable_pg_extensions, disable_pg_extensions),
        
        # Address model
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_type', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('billing', 'Billing'), ('shipping', 'Shipping'), ('other', 'Other')], max_length=30)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('landmark', models.CharField(blank=True, max_length=255)),
                ('locality', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('district', models.CharField(blank=True, max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('postal_code', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=2)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('geocoded', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        
        # ClinicalInsight model with pgvector embedding
        migrations.CreateModel(
            name='ClinicalInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('school', 'School'), ('medical', 'Medical'), ('psychological', 'Psychological'), ('career', 'Career'), ('relationship', 'Relationship')], db_index=True, max_length=20)),
                ('pattern', models.TextField()),
                ('recommendation', models.TextField()),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clinical Insight',
                'verbose_name_plural': 'Clinical Insights',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['session_type', '-created_at'], name='common_clin_session_idx'),
                    models.Index(fields=['confidence_score'], name='common_clin_confidence_idx'),
                ],
            },
        ),
        
        # Address.user foreign key
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
    ]